name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.SECRET_REPO }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

